set_property IOSTANDARD LVCMOS18 [get_ports oled_spi_clk_0]
set_property IOSTANDARD LVCMOS18 [get_ports oled_rst_n_0]
set_property IOSTANDARD LVCMOS18 [get_ports oled_dc_n_0]
set_property IOSTANDARD LVCMOS18 [get_ports oled_spi_data_0]
set_property IOSTANDARD LVCMOS18 [get_ports oled_vbat_0]
set_property IOSTANDARD LVCMOS18 [get_ports oled_vdd_0]
set_property PACKAGE_PIN AB12 [get_ports oled_spi_clk_0]
set_property PACKAGE_PIN U9 [get_ports oled_rst_n_0]
set_property PACKAGE_PIN U10 [get_ports oled_dc_n_0]
set_property PACKAGE_PIN AA12 [get_ports oled_spi_data_0]
set_property PACKAGE_PIN U11 [get_ports oled_vbat_0]
set_property PACKAGE_PIN U12 [get_ports oled_vdd_0]


set_property PACKAGE_PIN Y9 [get_ports clock]
set_property PACKAGE_PIN T22 [get_ports done_send]
set_property PACKAGE_PIN T18 [get_ports load_data]
set_property PACKAGE_PIN P16 [get_ports reset]
set_property PACKAGE_PIN T21 [get_ports spi_clock]
set_property PACKAGE_PIN U22 [get_ports spi_data]
set_property PACKAGE_PIN F22 [get_ports {data_in[0]}]
set_property PACKAGE_PIN G22 [get_ports {data_in[1]}]
set_property PACKAGE_PIN H22 [get_ports {data_in[2]}]
set_property PACKAGE_PIN F21 [get_ports {data_in[3]}]
set_property PACKAGE_PIN H19 [get_ports {data_in[4]}]
set_property PACKAGE_PIN H18 [get_ports {data_in[5]}]
set_property PACKAGE_PIN H17 [get_ports {data_in[6]}]
set_property PACKAGE_PIN M15 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports done_send]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports load_data]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports spi_clock]
set_property IOSTANDARD LVCMOS18 [get_ports spi_data]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {state[0]} {state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {data_in_IBUF[0]} {data_in_IBUF[1]} {data_in_IBUF[2]} {data_in_IBUF[3]} {data_in_IBUF[4]} {data_in_IBUF[5]} {data_in_IBUF[6]} {data_in_IBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list done_send_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list load_data_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list spi_clock_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list spi_data_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clock_IBUF_BUFG]
